### ISSUE TITLE
Don't work in Android GitHub application.

### ISSUE THREAD

**Issue by vector1dev** [SWCS3/my-socnets-username#1]
![photo_2022-01-23_13-11-14](https://user-images.githubusercontent.com/98253979/150673821-d9270776-726c-454e-9eff-da5f0f1caaf5.jpg)

**Comment by SWCS3** [comment]
Hello. I don't know what it is related to, but I will try to solve this problem. thanks for the warning

**Comment by SWCS3** [comment]
Hey. everything is working fine. ![Screenshot_20220123-133423_GitHub.png](https://user-images.githubusercontent.com/60889521/150676471-67f50958-4a41-4a4d-8ccf-85a0eb1bca18.png)
